name: Sync LeetCode

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/leetcode-github-actions@main
        with:
          username: shourish356
          commit_message: "update leetcode solutions"
