name: Sync LeetCode

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: leetcode-tools/leetcode-sync@main
        with:
          username: shourish356
